### PR TITLE
Pass variables to result function

### PR DESCRIPTION
**Pull request by ajdean**
Thought it would be handy when using a result function to be able to pass the query variables into the function, so they could be used to help generate the mock data.

Had a go at updating the code to make it so and it seems to work OK. Have also added a test around the functionality.

### CODE REVIEW

**Comment by insidewhy** [comment]
This is cool.

**Comment by insidewhy** [comment]
BTW your commit messages are in a mixture of imperative mood and declarative mood :D Most organisations seem to be mandating imperative right now, using that for this repo.

**Comment by eli0shin** [comment]
@insidewhy Thanks for this package, it makes working with apollo mocks much easier. Any idea when we might see a release or beta with this PR included?

**Comment by insidewhy** [comment]
@ajdean @eli0shin sorry I intended to release 2.0.1 with this two weeks ago, I'll do it today.

**Comment by insidewhy** [comment]
@ajdean @eli0shin Released 2.0.1. I think the built-in mock link should be replaced with wildcard-mock-link so I opened this feature request apollo: https://github.com/apollographql/apollo-feature-requests/issues/298

Would appreciate your reactions or comments on that issue. Thanks again for your contributions!

**Pull request merged**
