### PR TITLE
Normalize mocked response queries by removing @client directives

### PR DESCRIPTION
**Pull request by chuksynaza**
Ran into issues with wildcard-mock-link not matching queries that had local only fields.

This might be a fix for that problem.

This was quickly cooked up, so let me know if any improvements are needed

Is it also worth considering removing the connection directive as well? [https://github.com/apollographql/apollo-client/blob/fb9d0db6e7e465995190161cbfcb519a586f3701/src/utilities/testing/mocking/mockLink.ts#L158](https://github.com/apollographql/apollo-client/blob/fb9d0db6e7e465995190161cbfcb519a586f3701/src/utilities/testing/mocking/mockLink.ts#L158)

### CODE REVIEW

**Comment by insidewhy** [comment]
Cool thanks! I'll merge this and publish a new release tomorrow.

**Comment by chuksynaza** [comment]
Have you taken time to look at this yet? :-)

**Comment by insidewhy** [comment]
There's a lint error in this that broke CI, I'll fix that and then release.

**Comment by chuksynaza** [comment]
Created [this PR https://github.com/insidewhy/wildcard-mock-link/pull/113](https://github.com/insidewhy/wildcard-mock-link/pull/113) to fix that. Have a look and enjoy your weekend!

**Comment by chuksynaza** [comment]
Had time to look at this yet? :-P

**Comment by insidewhy** [comment]
@chuksynaza Published 2.0.2 with this change, sorry for the delay!

**Pull request merged**
